"use strict";

function Pregunta(categoria, tema, enunciado, opciones, correcta) {
    this.categoria = categoria;
    this.tema = tema;
    this.pregunta = enunciado;
    this.opciones = opciones;
    this.correcta = correcta;
}

var bancoPreguntas = [
    new Pregunta("mundial-1986", "campeon", "¿Quién fue el campeón del Mundial de 1986?", ["Alemania Occidental", "Brasil", "Argentina", "Italia"], 2),
    new Pregunta("historico", "goleador-historico", "¿Quién es el máximo goleador histórico de los Mundiales?", ["Ronaldo Nazário", "Miroslav Klose", "Pelé", "Gerd Müller"], 1),
    new Pregunta("mundial-2022", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial 2022?", ["Kylian Mbappé", "Lionel Messi", "Julián Álvarez", "Olivier Giroud"], 0),
    new Pregunta("mundial-2022", "balon-de-oro", "¿Quién ganó el Balón de Oro (mejor jugador) del Mundial 2022?", ["Kylian Mbappé", "Luka Modrić", "Lionel Messi", "Antoine Griezmann"], 2),
    new Pregunta("mundial-1990", "campeon", "¿Quién fue el campeón del Mundial de 1990?", ["Argentina", "Alemania Occidental", "Italia", "Brasil"], 1),
    new Pregunta("mundial-1930", "sede", "¿Dónde se disputó el primer Mundial, en 1930?", ["Brasil", "Italia", "Argentina", "Uruguay"], 3),
    new Pregunta("historico", "titulos-por-seleccion", "¿Cuántos Mundiales ganó la selección de España?", ["1", "2", "0", "3"], 0),
    new Pregunta("historico", "titulos-por-seleccion", "¿Cuál selección ganó más Mundiales en la historia?", ["Alemania", "Italia", "Brasil", "Argentina"], 2),
    new Pregunta("historico", "finales-por-seleccion", "¿Cuántas finales de Mundial disputó la selección argentina (hasta 2022)?", ["4", "6", "5", "7"], 1),
    new Pregunta("mundial-2014", "eliminacion", "¿En qué instancia quedó eliminada Brasil en el Mundial 2014?", ["Cuartos de final", "Octavos de final", "Final", "Semifinales"], 3),
    new Pregunta("historico", "record-partido", "¿Cuál fue el partido con más goles en la historia de los Mundiales?", ["Austria 7-5 Suiza (1954)", "Hungría 10-1 El Salvador (1982)", "Alemania 7-1 Brasil (2014)", "Yugoslavia 9-0 Zaire (1974)"], 0),
    new Pregunta("historico", "anios-no-disputados", "¿En qué años no se disputó la Copa del Mundo debido a la Segunda Guerra Mundial?", ["1938 y 1942", "1946 y 1950", "1942 y 1946", "1940 y 1944"], 2),
    new Pregunta("historico", "primer-mundial", "¿En qué año se disputó el primer Mundial de la historia?", ["1928", "1930", "1934", "1926"], 1),
    new Pregunta("historico", "balones-de-oro-jugador", "¿Qué jugador ganó el Balón de Oro del Mundial en dos ediciones distintas?", ["Pelé", "Zinedine Zidane", "Ronaldo Nazário", "Diego Maradona"], 3),
    new Pregunta("mundial-2022", "guante-de-oro", "¿Quién ganó el Guante de Oro (mejor arquero) del Mundial 2022?", ["Emiliano Martínez", "Hugo Lloris", "Alisson Becker", "Yassine Bounou"], 0),
    new Pregunta("mundial-2018", "campeon", "¿Quién fue el campeón del Mundial de 2018?", ["Croacia", "Bélgica", "Francia", "Inglaterra"], 2),
    new Pregunta("mundial-2014", "goleador-mundial", "¿Quién fue el máximo goleador (Bota de Oro) del Mundial 2014?", ["Neymar", "James Rodríguez", "Thomas Müller", "Lionel Messi"], 1),
    new Pregunta("mundial-2006", "campeon", "¿Quién fue el campeón del Mundial de 2006?", ["Francia", "Alemania", "Brasil", "Italia"], 3),
    new Pregunta("mundial-2018", "eliminacion", "¿Qué selección eliminó a Argentina en el Mundial 2018?", ["Francia", "Croacia", "Uruguay", "Bélgica"], 0),

    new Pregunta("mundial-1930", "campeon", "¿Quién fue el campeón del Mundial de 1930?", ["Argentina", "Estados Unidos", "Uruguay", "Brasil"], 2),
    new Pregunta("mundial-1934", "campeon", "¿Quién fue el campeón del Mundial de 1934?", ["Checoslovaquia", "Italia", "Austria", "Alemania"], 1),
    new Pregunta("mundial-1938", "campeon", "¿Quién fue el campeón del Mundial de 1938?", ["Hungría", "Brasil", "Suecia", "Italia"], 3),
    new Pregunta("mundial-1950", "campeon", "¿Quién fue el campeón del Mundial de 1950?", ["Brasil", "España", "Suecia", "Uruguay"], 3),
    new Pregunta("mundial-1954", "campeon", "¿Quién fue el campeón del Mundial de 1954?", ["Hungría", "Alemania Occidental", "Austria", "Uruguay"], 1),
    new Pregunta("mundial-1958", "campeon", "¿Quién fue el campeón del Mundial de 1958?", ["Suecia", "Francia", "Brasil", "Alemania Occidental"], 2),
    new Pregunta("mundial-1962", "campeon", "¿Quién fue el campeón del Mundial de 1962?", ["Checoslovaquia", "Chile", "Yugoslavia", "Brasil"], 3),
    new Pregunta("mundial-1966", "campeon", "¿Quién fue el campeón del Mundial de 1966?", ["Alemania Occidental", "Inglaterra", "Portugal", "Unión Soviética"], 1),
    new Pregunta("mundial-1970", "campeon", "¿Quién fue el campeón del Mundial de 1970?", ["Italia", "Alemania Occidental", "Brasil", "Uruguay"], 2),
    new Pregunta("mundial-1974", "campeon", "¿Quién fue el campeón del Mundial de 1974?", ["Países Bajos", "Polonia", "Alemania Occidental", "Brasil"], 2),
    new Pregunta("mundial-1978", "campeon", "¿Quién fue el campeón del Mundial de 1978?", ["Países Bajos", "Brasil", "Argentina", "Italia"], 2),
    new Pregunta("mundial-1982", "campeon", "¿Quién fue el campeón del Mundial de 1982?", ["Alemania Occidental", "Italia", "Polonia", "Francia"], 1),
    new Pregunta("mundial-1994", "campeon", "¿Quién fue el campeón del Mundial de 1994?", ["Italia", "Brasil", "Suecia", "Bulgaria"], 1),
    new Pregunta("mundial-1998", "campeon", "¿Quién fue el campeón del Mundial de 1998?", ["Brasil", "Croacia", "Francia", "Países Bajos"], 2),
    new Pregunta("mundial-2002", "campeon", "¿Quién fue el campeón del Mundial de 2002?", ["Alemania", "Turquía", "Brasil", "Corea del Sur"], 2),
    new Pregunta("mundial-2010", "campeon", "¿Quién fue el campeón del Mundial de 2010?", ["Países Bajos", "Alemania", "España", "Uruguay"], 2),
    new Pregunta("mundial-2014", "campeon", "¿Quién fue el campeón del Mundial de 2014?", ["Argentina", "Alemania", "Países Bajos", "Brasil"], 1),
    new Pregunta("mundial-2022", "campeon", "¿Quién fue el campeón del Mundial de 2022?", ["Francia", "Argentina", "Croacia", "Marruecos"], 1),

    new Pregunta("mundial-1934", "sede", "¿Dónde se disputó el Mundial de 1934?", ["Francia", "Italia", "España", "Suiza"], 1),
    new Pregunta("mundial-1938", "sede", "¿Dónde se disputó el Mundial de 1938?", ["Italia", "Bélgica", "Francia", "Suiza"], 2),
    new Pregunta("mundial-1950", "sede", "¿Dónde se disputó el Mundial de 1950?", ["Argentina", "Uruguay", "Chile", "Brasil"], 3),
    new Pregunta("mundial-1954", "sede", "¿Dónde se disputó el Mundial de 1954?", ["Austria", "Suiza", "Alemania Occidental", "Hungría"], 1),
    new Pregunta("mundial-1958", "sede", "¿Dónde se disputó el Mundial de 1958?", ["Noruega", "Suecia", "Dinamarca", "Finlandia"], 1),
    new Pregunta("mundial-1962", "sede", "¿Dónde se disputó el Mundial de 1962?", ["Perú", "Argentina", "Chile", "Brasil"], 2),
    new Pregunta("mundial-1966", "sede", "¿Dónde se disputó el Mundial de 1966?", ["Escocia", "Inglaterra", "Francia", "Alemania Occidental"], 1),
    new Pregunta("mundial-1970", "sede", "¿Dónde se disputó el Mundial de 1970?", ["Estados Unidos", "Brasil", "México", "Colombia"], 2),
    new Pregunta("mundial-1974", "sede", "¿Dónde se disputó el Mundial de 1974?", ["Alemania del Este", "Países Bajos", "Alemania Occidental", "Bélgica"], 2),
    new Pregunta("mundial-1978", "sede", "¿Dónde se disputó el Mundial de 1978?", ["Brasil", "Argentina", "Uruguay", "Chile"], 1),
    new Pregunta("mundial-1982", "sede", "¿Dónde se disputó el Mundial de 1982?", ["Portugal", "Italia", "España", "Francia"], 2),
    new Pregunta("mundial-1986", "sede", "¿Dónde se disputó el Mundial de 1986?", ["Colombia", "México", "Estados Unidos", "Brasil"], 1),
    new Pregunta("mundial-1994", "sede", "¿Dónde se disputó el Mundial de 1994?", ["México", "Marruecos", "Estados Unidos", "Brasil"], 2),
    new Pregunta("mundial-1998", "sede", "¿Dónde se disputó el Mundial de 1998?", ["Marruecos", "Francia", "España", "Suiza"], 1),
    new Pregunta("mundial-2002", "sede", "¿Dónde se disputó el Mundial de 2002?", ["Japón", "Corea del Sur y Japón", "China", "Corea del Norte"], 1),

    new Pregunta("mundial-1930", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1930?", ["Pedro Cea", "José Nasazzi", "Guillermo Stábile", "Héctor Castro"], 2),
    new Pregunta("mundial-1934", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1934?", ["Angelo Schiavio", "Oldřich Nejedlý", "Edmund Conen", "Leônidas"], 1),
    new Pregunta("mundial-1938", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1938?", ["Silvio Piola", "Gyula Zsengellér", "Leônidas", "Ademir"], 2),
    new Pregunta("mundial-1950", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1950?", ["Alcides Ghiggia", "Ademir", "Óscar Míguez", "Zizinho"], 1),
    new Pregunta("mundial-1954", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1954?", ["Ferenc Puskás", "Max Morlock", "Sándor Kocsis", "Helmut Rahn"], 2),
    new Pregunta("mundial-1958", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1958, con 13 goles (récord histórico en una sola edición)?", ["Pelé", "Just Fontaine", "Vavá", "Didi"], 1),
    new Pregunta("mundial-1966", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1966?", ["Bobby Charlton", "Geoff Hurst", "Eusébio", "Franz Beckenbauer"], 2),
    new Pregunta("mundial-1970", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1970?", ["Pelé", "Jairzinho", "Gerd Müller", "Rivelino"], 2),
    new Pregunta("mundial-1974", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1974?", ["Johan Cruyff", "Grzegorz Lato", "Andrzej Szarmach", "Paul Breitner"], 1),
    new Pregunta("mundial-1978", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1978?", ["Rob Rensenbrink", "Mario Kempes", "Teófilo Cubillas", "Leopoldo Luque"], 1),
    new Pregunta("mundial-1982", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1982?", ["Zico", "Karl-Heinz Rummenigge", "Paolo Rossi", "Zbigniew Boniek"], 2),
    new Pregunta("mundial-1986", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1986?", ["Diego Maradona", "Gary Lineker", "Emilio Butragueño", "Careca"], 1),
    new Pregunta("mundial-1990", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1990?", ["Roger Milla", "Lothar Matthäus", "Salvatore Schillaci", "Diego Maradona"], 2),
    new Pregunta("mundial-1994", "record-partido", "¿Qué jugador ruso marcó 5 goles en un único partido del Mundial de 1994 (récord histórico vigente)?", ["Romário", "Roberto Baggio", "Hristo Stoichkov", "Oleg Salenko"], 3),
    new Pregunta("mundial-1998", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1998?", ["Ronaldo Nazário", "Davor Šuker", "Zinedine Zidane", "Michael Owen"], 1),
    new Pregunta("mundial-2002", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 2002?", ["Miroslav Klose", "Ronaldo Nazário", "Rivaldo", "Oliver Kahn"], 1),
    new Pregunta("mundial-2006", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 2006?", ["Thierry Henry", "Zinedine Zidane", "Miroslav Klose", "Fabio Grosso"], 2),
    new Pregunta("mundial-2010", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 2010?", ["Diego Forlán", "David Villa", "Thomas Müller", "Wesley Sneijder"], 2),

    new Pregunta("historico", "record-jugador", "¿Qué jugador tiene el récord de más partidos disputados en la historia de los Mundiales?", ["Lothar Matthäus", "Cristiano Ronaldo", "Diego Maradona", "Lionel Messi"], 3),
    new Pregunta("historico", "participacion-perfecta", "¿Qué selección jugó todas las ediciones de la Copa del Mundo sin faltar nunca?", ["Alemania", "Italia", "Argentina", "Brasil"], 3),
    new Pregunta("mundial-1930", "participantes", "¿Cuántas selecciones participaron en la fase final del primer Mundial (1930)?", ["16", "8", "13", "24"], 2),
    new Pregunta("historico", "ampliacion-formato", "¿A partir de qué Mundial la fase final pasó a tener 32 selecciones?", ["1994", "1998", "2002", "1990"], 1),
    new Pregunta("historico", "record-goles-partido", "¿En qué partido una selección marcó 10 goles, la mayor cantidad convertida por un equipo en un partido de Mundial?", ["Alemania 8-0 Arabia Saudita (2002)", "Yugoslavia 9-0 Zaire (1974)", "Hungría 10-1 El Salvador (1982)", "Hungría 9-0 Corea del Sur (1954)"], 2),
    new Pregunta("mundial-2006", "expulsion-final", "¿Qué jugador francés fue expulsado en la final del Mundial 2006?", ["Marco Materazzi", "Thierry Henry", "Fabio Cannavaro", "Zinedine Zidane"], 3),
    new Pregunta("mundial-1966", "hat-trick-final", "¿Qué jugador inglés marcó el primer hat-trick en una final de Mundial, en 1966?", ["Bobby Moore", "Bobby Charlton", "Geoff Hurst", "Franz Beckenbauer"], 2),
    new Pregunta("historico", "finales-consecutivas", "¿Qué jugador brasileño disputó tres finales de Mundial consecutivas (1994, 1998 y 2002)?", ["Ronaldo Nazário", "Roberto Carlos", "Cafu", "Ronaldinho"], 2),
    new Pregunta("historico", "penales-en-finales", "¿Cuántas finales de Mundial se definieron por penales hasta 2022?", ["1", "2", "3", "4"], 2),
    new Pregunta("mundial-1950", "formato", "¿Qué particularidad tuvo el Mundial de 1950 respecto a la definición del campeón?", ["Se definió por sorteo", "Se definió por penales", "Se definió por una rueda final todos contra todos", "Se definió por un desempate a partido único"], 2),
    new Pregunta("historico", "jugador-joven", "¿Quién es el jugador más joven en marcar un gol en la historia de los Mundiales?", ["Diego Maradona", "Kylian Mbappé", "Pelé", "Michael Owen"], 2),
    new Pregunta("historico", "jugador-joven", "¿Quién es el jugador más joven en salir campeón del mundo?", ["Kylian Mbappé", "Franz Beckenbauer", "Bobby Moore", "Pelé"], 3),
    new Pregunta("historico", "arbitraje", "¿En qué Mundial se utilizó por primera vez el VAR (videoarbitraje)?", ["2014", "2018", "2022", "2010"], 1),
    new Pregunta("historico", "transmision", "¿Cuál fue el primer Mundial transmitido en color y vía satélite a todo el mundo?", ["1966", "1970", "1974", "1978"], 1),
    new Pregunta("mundial-1934", "final-historica", "¿Cuál fue la primera final de un Mundial disputada entre dos selecciones europeas?", ["1930", "1934", "1938", "1950"], 1),
    new Pregunta("historico", "anecdota-trofeo", "¿Cómo se llamaba el perro que encontró la Copa Jules Rimet tras ser robada antes del Mundial de 1966?", ["Rex", "Pickles", "Toby", "Fido"], 1),
    new Pregunta("historico", "trofeo", "¿Por qué Brasil se quedó en propiedad definitiva con el trofeo original (Copa Jules Rimet) tras 1970?", ["Por ser el país organizador ese año", "Por ser la primera selección en ganar 3 Copas del Mundo", "Por decisión de la FIFA tras un sorteo", "Por haber ganado 3 finales consecutivas"], 1),
    new Pregunta("historico", "trofeo", "¿Desde qué Mundial se entrega el trofeo actual de la FIFA, que reemplazó a la Copa Jules Rimet?", ["1970", "1974", "1978", "1982"], 1),
    new Pregunta("mundial-1986", "sede-renuncia", "¿Qué selección iba a ser sede original del Mundial de 1986 y renunció por motivos económicos?", ["Argentina", "Brasil", "Estados Unidos", "Colombia"], 3)
];
