"use strict";

function Pregunta(categoria, tema, enunciado, opciones, correcta) {
    this.categoria = categoria;
    this.tema = tema;
    this.pregunta = enunciado;
    this.opciones = opciones;
    this.correcta = correcta;
}

var bancoPreguntas = [
    new Pregunta("mundial-1986", "campeon", "¿Quién fue el campeón del Mundial de 1986?", ["Alemania Occidental", "Brasil", "Argentina", "Italia"], 2),
    new Pregunta("historico", "goleador-historico", "¿Quién es el máximo goleador histórico de los Mundiales?", ["Kylian Mbappé", "Miroslav Klose", "Pelé", "Gerd Müller"], 0),
    new Pregunta("mundial-2022", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial 2022?", ["Kylian Mbappé", "Lionel Messi", "Julián Álvarez", "Olivier Giroud"], 0),
    new Pregunta("mundial-2022", "balon-de-oro", "¿Quién ganó el Balón de Oro (mejor jugador) del Mundial 2022?", ["Kylian Mbappé", "Luka Modrić", "Lionel Messi", "Antoine Griezmann"], 2),
    new Pregunta("mundial-1990", "campeon", "¿Quién fue el campeón del Mundial de 1990?", ["Argentina", "Alemania Occidental", "Italia", "Brasil"], 1),
    new Pregunta("mundial-1930", "sede", "¿Dónde se disputó el Mundial en 1930?", ["Brasil", "Italia", "Argentina", "Uruguay"], 3),
    new Pregunta("historico", "titulos-por-seleccion", "¿Cuántos Mundiales ganó la selección de España?", ["2", "1", "0", "3"], 0),
    new Pregunta("historico", "titulos-por-seleccion", "¿Cuál selección ganó más Mundiales en la historia?", ["Alemania", "Italia", "Brasil", "Argentina"], 2),
    new Pregunta("historico", "finales-por-seleccion", "¿Cuántas finales de Mundial disputó la selección argentina (hasta 2026)?", ["4", "6", "5", "7"], 3),
    new Pregunta("mundial-2014", "eliminacion", "¿En qué instancia quedó eliminada Brasil en el Mundial 2014?", ["Cuartos de final", "Octavos de final", "Final", "Semifinales"], 3),
    new Pregunta("historico", "record-partido", "¿Cuál fue el partido con más goles en la historia de los Mundiales?", ["Austria - Suiza (1954)", "Hungría - El Salvador (1982)", "Alemania - Brasil (2014)", "Yugoslavia - Zaire (1974)"], 0),
    new Pregunta("historico", "anios-no-disputados", "¿En qué años no se disputó la Copa del Mundo debido a la Segunda Guerra Mundial?", ["1938 y 1942", "1946 y 1950", "1942 y 1946", "1940 y 1944"], 2),
    new Pregunta("historico", "primer-mundial", "¿En qué año se disputó el primer Mundial de la historia?", ["1928", "1930", "1934", "1926"], 1),
    new Pregunta("historico", "balones-de-oro-jugador", "¿Qué jugador ganó el Balón de Oro del Mundial en dos ediciones distintas?", ["Pelé", "Zinedine Zidane", "Ronaldo Nazário", "Diego Maradona"], 3),
    new Pregunta("mundial-2022", "guante-de-oro", "¿Quién ganó el Guante de Oro (mejor arquero) del Mundial 2022?", ["Emiliano Martínez", "Hugo Lloris", "Alisson Becker", "Yassine Bounou"], 0),
    new Pregunta("mundial-2018", "campeon", "¿Quién fue el campeón del Mundial de 2018?", ["Croacia", "Bélgica", "Francia", "Inglaterra"], 2),
    new Pregunta("mundial-2014", "goleador-mundial", "¿Quién fue el máximo goleador (Bota de Oro) del Mundial 2014?", ["Neymar", "James Rodríguez", "Thomas Müller", "Lionel Messi"], 1),
    new Pregunta("mundial-2006", "campeon", "¿Quién fue el campeón del Mundial de 2006?", ["Francia", "Alemania", "Brasil", "Italia"], 3),
    new Pregunta("mundial-2018", "eliminacion", "¿Qué selección eliminó a Argentina en el Mundial 2018?", ["Francia", "Croacia", "Uruguay", "Bélgica"], 0),

    new Pregunta("mundial-1930", "campeon", "¿Quién fue el campeón del Mundial de 1930?", ["Argentina", "Estados Unidos", "Uruguay", "Brasil"], 2),
    new Pregunta("mundial-1934", "campeon", "¿Quién fue el campeón del Mundial de 1934?", ["Checoslovaquia", "Italia", "Austria", "Alemania"], 1),
    new Pregunta("mundial-1938", "campeon", "¿Quién fue el campeón del Mundial de 1938?", ["Hungría", "Brasil", "Suecia", "Italia"], 3),
    new Pregunta("mundial-1950", "campeon", "¿Quién fue el campeón del Mundial de 1950?", ["Brasil", "España", "Suecia", "Uruguay"], 3),
    new Pregunta("mundial-1954", "campeon", "¿Quién fue el campeón del Mundial de 1954?", ["Hungría", "Alemania Occidental", "Austria", "Uruguay"], 1),
    new Pregunta("mundial-1958", "campeon", "¿Quién fue el campeón del Mundial de 1958?", ["Suecia", "Francia", "Brasil", "Alemania Occidental"], 2),
    new Pregunta("mundial-1962", "campeon", "¿Quién fue el campeón del Mundial de 1962?", ["Italia", "Uruguay", "Alemania Federal", "Brasil"], 3),
    new Pregunta("mundial-1966", "campeon", "¿Quién fue el campeón del Mundial de 1966?", ["Alemania Occidental", "Inglaterra", "Portugal", "Unión Soviética"], 1),
    new Pregunta("mundial-1970", "campeon", "¿Quién fue el campeón del Mundial de 1970?", ["Italia", "Alemania Occidental", "Brasil", "Uruguay"], 2),
    new Pregunta("mundial-1974", "campeon", "¿Quién fue el campeón del Mundial de 1974?", ["Países Bajos", "Polonia", "Alemania Occidental", "Brasil"], 2),
    new Pregunta("mundial-1978", "campeon", "¿Quién fue el campeón del Mundial de 1978?", ["Países Bajos", "Brasil", "Argentina", "Italia"], 2),
    new Pregunta("mundial-1982", "campeon", "¿Quién fue el campeón del Mundial de 1982?", ["Alemania Occidental", "Italia", "Polonia", "Francia"], 1),
    new Pregunta("mundial-1994", "campeon", "¿Quién fue el campeón del Mundial de 1994?", ["Italia", "Brasil", "Suecia", "Bulgaria"], 1),
    new Pregunta("mundial-1998", "campeon", "¿Quién fue el campeón del Mundial de 1998?", ["Brasil", "Croacia", "Francia", "Países Bajos"], 2),
    new Pregunta("mundial-2002", "campeon", "¿Quién fue el campeón del Mundial de 2002?", ["Alemania", "Turquía", "Brasil", "Corea del Sur"], 2),
    new Pregunta("mundial-2010", "campeon", "¿Quién fue el campeón del Mundial de 2010?", ["Países Bajos", "Alemania", "España", "Uruguay"], 2),
    new Pregunta("mundial-2014", "campeon", "¿Quién fue el campeón del Mundial de 2014?", ["Argentina", "Alemania", "Países Bajos", "Brasil"], 1),
    new Pregunta("mundial-2022", "campeon", "¿Quién fue el campeón del Mundial de 2022?", ["Francia", "Argentina", "Croacia", "Marruecos"], 1),

    new Pregunta("mundial-1934", "sede", "¿Dónde se disputó el Mundial de 1934?", ["Francia", "Italia", "España", "Suiza"], 1),
    new Pregunta("mundial-1938", "sede", "¿Dónde se disputó el Mundial de 1938?", ["Italia", "Bélgica", "Francia", "Suiza"], 2),
    new Pregunta("mundial-1950", "sede", "¿Dónde se disputó el Mundial de 1950?", ["Argentina", "Uruguay", "Chile", "Brasil"], 3),
    new Pregunta("mundial-1954", "sede", "¿Dónde se disputó el Mundial de 1954?", ["Austria", "Suiza", "Alemania Occidental", "Hungría"], 1),
    new Pregunta("mundial-1958", "sede", "¿Dónde se disputó el Mundial de 1958?", ["Noruega", "Suecia", "Dinamarca", "Finlandia"], 1),
    new Pregunta("mundial-1962", "sede", "¿Dónde se disputó el Mundial de 1962?", ["Perú", "Argentina", "Chile", "Brasil"], 2),
    new Pregunta("mundial-1966", "sede", "¿Dónde se disputó el Mundial de 1966?", ["Escocia", "Inglaterra", "Francia", "Alemania Occidental"], 1),
    new Pregunta("mundial-1970", "sede", "¿Dónde se disputó el Mundial de 1970?", ["Estados Unidos", "Brasil", "México", "Colombia"], 2),
    new Pregunta("mundial-1974", "sede", "¿Dónde se disputó el Mundial de 1974?", ["Alemania del Este", "Países Bajos", "Alemania Occidental", "Bélgica"], 2),
    new Pregunta("mundial-1978", "sede", "¿Dónde se disputó el Mundial de 1978?", ["Brasil", "Argentina", "Uruguay", "Chile"], 1),
    new Pregunta("mundial-1982", "sede", "¿Dónde se disputó el Mundial de 1982?", ["Portugal", "Italia", "España", "Francia"], 2),
    new Pregunta("mundial-1986", "sede", "¿Dónde se disputó el Mundial de 1986?", ["Colombia", "México", "Estados Unidos", "Brasil"], 1),
    new Pregunta("mundial-1994", "sede", "¿Dónde se disputó el Mundial de 1994?", ["México", "Marruecos", "Estados Unidos", "Brasil"], 2),
    new Pregunta("mundial-1998", "sede", "¿Dónde se disputó el Mundial de 1998?", ["Marruecos", "Francia", "España", "Suiza"], 1),
    new Pregunta("mundial-2002", "sede", "¿Dónde se disputó el Mundial de 2002?", ["Japón", "Corea del Sur y Japón", "China", "Corea del Norte"], 1),

    new Pregunta("mundial-1930", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1930?", ["Pedro Cea", "José Nasazzi", "Guillermo Stábile", "Héctor Castro"], 2),
    new Pregunta("mundial-1934", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1934?", ["Angelo Schiavio", "Oldřich Nejedlý", "Edmund Conen", "Leônidas"], 1),
    new Pregunta("mundial-1938", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1938?", ["Silvio Piola", "Gyula Zsengellér", "Leônidas", "Ademir"], 2),
    new Pregunta("mundial-1950", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1950?", ["Alcides Ghiggia", "Ademir", "Óscar Míguez", "Zizinho"], 1),
    new Pregunta("mundial-1954", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1954?", ["Ferenc Puskás", "Max Morlock", "Sándor Kocsis", "Helmut Rahn"], 2),
    new Pregunta("mundial-1958", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1958, con 13 goles (récord histórico en una sola edición)?", ["Pelé", "Just Fontaine", "Vavá", "Didi"], 1),
    new Pregunta("mundial-1966", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1966?", ["Bobby Charlton", "Geoff Hurst", "Eusébio", "Franz Beckenbauer"], 2),
    new Pregunta("mundial-1970", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1970?", ["Pelé", "Jairzinho", "Gerd Müller", "Rivelino"], 2),
    new Pregunta("mundial-1974", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1974?", ["Johan Cruyff", "Grzegorz Lato", "Andrzej Szarmach", "Paul Breitner"], 1),
    new Pregunta("mundial-1978", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1978?", ["Rob Rensenbrink", "Mario Kempes", "Teófilo Cubillas", "Leopoldo Luque"], 1),
    new Pregunta("mundial-1982", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1982?", ["Zico", "Karl-Heinz Rummenigge", "Paolo Rossi", "Zbigniew Boniek"], 2),
    new Pregunta("mundial-1986", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1986?", ["Diego Maradona", "Gary Lineker", "Emilio Butragueño", "Careca"], 1),
    new Pregunta("mundial-1990", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1990?", ["Roger Milla", "Lothar Matthäus", "Salvatore Schillaci", "Diego Maradona"], 2),
    new Pregunta("mundial-1994", "record-partido", "¿Qué jugador ruso marcó 5 goles en un único partido del Mundial de 1994 (récord histórico vigente)?", ["Romário", "Roberto Baggio", "Hristo Stoichkov", "Oleg Salenko"], 3),
    new Pregunta("mundial-1998", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 1998?", ["Ronaldo Nazário", "Davor Šuker", "Zinedine Zidane", "Michael Owen"], 1),
    new Pregunta("mundial-2002", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 2002?", ["Miroslav Klose", "Ronaldo Nazário", "Rivaldo", "Oliver Kahn"], 1),
    new Pregunta("mundial-2006", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 2006?", ["Thierry Henry", "Zinedine Zidane", "Miroslav Klose", "Fabio Grosso"], 2),
    new Pregunta("mundial-2010", "goleador-mundial", "¿Quién fue el máximo goleador del Mundial de 2010?", ["Diego Forlán", "David Villa", "Thomas Müller", "Wesley Sneijder"], 2),

    new Pregunta("historico", "record-jugador", "¿Qué jugador tiene el récord de más partidos disputados en la historia de los Mundiales?", ["Lothar Matthäus", "Cristiano Ronaldo", "Diego Maradona", "Lionel Messi"], 3),
    new Pregunta("historico", "participacion-perfecta", "¿Qué selección jugó todas las ediciones de la Copa del Mundo sin faltar nunca?", ["Alemania", "Italia", "Argentina", "Brasil"], 3),
    new Pregunta("mundial-1930", "participantes", "¿Cuántas selecciones participaron en la fase final del primer Mundial (1930)?", ["16", "8", "13", "24"], 2),
    new Pregunta("historico", "ampliacion-formato", "¿A partir de qué Mundial la fase final pasó a tener 32 selecciones?", ["1994", "1998", "2002", "1990"], 1),
    new Pregunta("historico", "record-goles-partido", "¿En qué partido una selección marcó 10 goles, la mayor cantidad convertida por un equipo en un partido de Mundial?", ["Alemania - Arabia Saudita (2002)", "Yugoslavia - Zaire (1974)", "Hungría - El Salvador (1982)", "Hungría - Corea del Sur (1954)"], 2),
    new Pregunta("mundial-2006", "expulsion-final", "¿Qué jugador francés fue expulsado en la final del Mundial 2006?", ["Marco Materazzi", "Thierry Henry", "Fabio Cannavaro", "Zinedine Zidane"], 3),
    new Pregunta("mundial-1966", "hat-trick-final", "¿Qué jugador inglés marcó el primer hat-trick en una final de Mundial, en 1966?", ["Bobby Moore", "Bobby Charlton", "Geoff Hurst", "Franz Beckenbauer"], 2),
    new Pregunta("historico", "finales-consecutivas", "¿Qué jugador brasileño disputó tres finales de Mundial consecutivas (1994, 1998 y 2002)?", ["Ronaldo Nazário", "Roberto Carlos", "Cafu", "Ronaldinho"], 2),
    new Pregunta("historico", "penales-en-finales", "¿Cuántas finales de Mundial se definieron por penales hasta 2022?", ["1", "2", "3", "4"], 2),
    new Pregunta("mundial-1950", "formato", "¿Qué particularidad tuvo el Mundial de 1950 respecto a la definición del campeón?", ["Se definió por sorteo", "Se definió por penales", "Se definió por una rueda final todos contra todos", "Se definió por un desempate a partido único"], 2),
    new Pregunta("historico", "jugador-joven", "¿Quién es el jugador más joven en marcar un gol en la historia de los Mundiales?", ["Diego Maradona", "Kylian Mbappé", "Pelé", "Michael Owen"], 2),
    new Pregunta("historico", "jugador-joven", "¿Quién es el jugador más joven en salir campeón del mundo?", ["Kylian Mbappé", "Franz Beckenbauer", "Bobby Moore", "Pelé"], 3),
    new Pregunta("historico", "arbitraje", "¿En qué Mundial se utilizó por primera vez el VAR (videoarbitraje)?", ["2014", "2018", "2022", "2010"], 1),
    new Pregunta("historico", "transmision", "¿Cuál fue el primer Mundial transmitido en color y vía satélite a todo el mundo?", ["1966", "1970", "1974", "1978"], 1),
    new Pregunta("mundial-1934", "final-historica", "¿Cuál fue la primera final de un Mundial disputada entre dos selecciones europeas?", ["1930", "1934", "1938", "1950"], 1),
    new Pregunta("historico", "anecdota-trofeo", "¿Cómo se llamaba el perro que encontró la Copa Jules Rimet tras ser robada antes del Mundial de 1966?", ["Rex", "Pickles", "Toby", "Fido"], 1),
    new Pregunta("historico", "trofeo", "¿Por qué Brasil se quedó en propiedad definitiva con el trofeo original (Copa Jules Rimet) tras 1970?", ["Por ser el país organizador ese año", "Por ser la primera selección en ganar 3 Copas del Mundo", "Por decisión de la FIFA tras un sorteo", "Por haber ganado 3 finales consecutivas"], 1),
    new Pregunta("historico", "trofeo", "¿Desde qué Mundial se entrega el trofeo actual de la FIFA, que reemplazó a la Copa Jules Rimet?", ["1970", "1974", "1978", "1982"], 1),
    new Pregunta("mundial-1986", "sede-renuncia", "¿Qué selección iba a ser sede original del Mundial de 1986 y renunció por motivos económicos?", ["Argentina", "Brasil", "Estados Unidos", "Colombia"], 3),

    new Pregunta("mundial-2026", "sede", "¿Cuáles son los tres países anfitriones de la Copa del Mundo 2026?", ["Estados Unidos, México y Canadá", "Estados Unidos, México y Costa Rica", "Canadá, Estados Unidos y Jamaica", "México, Colombia y Estados Unidos"], 0),
    new Pregunta("mundial-2026", "participantes", "¿Cuántas selecciones participan en la fase final del Mundial 2026?", ["32", "40", "48", "64"], 2),
    new Pregunta("mundial-2026", "formato", "¿Cómo están organizados los grupos en la fase inicial del Mundial 2026?", ["8 grupos de 6 equipos", "16 grupos de 3 equipos", "12 grupos de 4 equipos", "10 grupos de 5 equipos"], 2),
    new Pregunta("mundial-2026", "sede-historica", "¿Qué hito histórico logró México al albergar partidos en el Mundial 2026?", ["Ser el primer país en albergar 3 Mundiales distintos", "Ser el único país en jugar todas las finales", "Ser la sede con más estadios en una sola edición", "Ser el primer país de Concacaf en ganar la copa"], 0),
    new Pregunta("mundial-2026", "estadio-final", "¿En qué estadio o área metropolitana se definió la final de la Copa del Mundo 2026?", ["Estadio Azteca (Ciudad de México)", "Estadio de Nueva York / Nueva Jersey", "SoFi Stadium (Los Ángeles)", "AT&T Stadium (Dallas)"], 1),
    new Pregunta("mundial-2026", "calendario", "¿Cuántos partidos en total se disputan en el formato ampliado del Mundial 2026?", ["64 partidos", "80 partidos", "104 partidos", "128 partidos"], 2),
    new Pregunta("mundial-2026", "formato", "¿Qué nueva instancia de eliminación directa se añadió en el Mundial 2026 gracias a la ampliación de cupos?", ["Dieciseisavos de final", "Treintaidosavos de final", "Ronda preliminar", "Ronda de consolación"], 0),
    new Pregunta("mundial-2026", "balon-de-oro", "¿Quién ganó el Balón de Oro al mejor jugador del Mundial 2026?", ["Lionel Messi", "Rodri", "Kylian Mbappé", "Jude Bellingham"], 1),
    new Pregunta("mundial-2026", "bota-de-oro", "¿Quién conquistó la Bota de Oro como máximo goleador del Mundial 2026 (con 10 goles)?", ["Kylian Mbappé", "Lionel Messi", "Erling Haaland", "Jude Bellingham"], 0),
    new Pregunta("mundial-2026", "guante-de-oro", "¿Quién obtuvo el Guante de Oro al mejor arquero del Mundial 2026?", ["Emiliano Martínez", "Unai Simón", "Gianluigi Donnarumma", "Thibaut Courtois"], 1),
    new Pregunta("mundial-2026", "jugador-joven", "¿Qué futbolista fue galardonado como el Mejor Jugador Joven del Mundial 2026?", ["Lamine Yamal", "Endrick", "Pau Cubarsí", "Jude Bellingham"], 2),
    new Pregunta("mundial-2026", "campeon", "¿Qué selección se consagró campeona del Mundial 2026?", ["Argentina", "Francia", "España", "Inglaterra"], 2),
    new Pregunta("mundial-2026", "resultado-final", "¿Cómo finalizó la gran final del Mundial 2026 entre España y Argentina?", ["España 1-0 Argentina (en tiempo suplementario)", "España 2-1 Argentina", "España 0-0 Argentina (4-2 en penales)", "Argentina 1-0 España"], 0),
    new Pregunta("mundial-2026", "tercer-puesto", "¿Qué selección se quedó con el tercer puesto en el Mundial 2026?", ["Francia", "Inglaterra", "Marruecos", "Bélgica"], 1),
    new Pregunta("mundial-2026", "resultado-tercer-puesto", "¿Cuál fue el abultado marcador en el partido por el tercer puesto entre Inglaterra y Francia en el Mundial 2026?", ["4-3", "5-3", "6-4", "3-2"], 2),
    new Pregunta("mundial-2026", "record-goleador-historico", "¿Qué jugador se convirtió en el máximo goleador histórico de la Copa del Mundo en 2026 al alcanzar los 22 goles totales?", ["Lionel Messi", "Cristiano Ronaldo", "Kylian Mbappé", "Miroslav Klose"], 2),

    new Pregunta("historico", "resultado-famoso", "¿Cuál fue el resultado final del histórico partido entre Argentina e Inglaterra en los cuartos de final de México 1986?", ["1-0", "2-1", "3-1", "2-0"], 1),
    new Pregunta("mundial-2022", "resultado-final", "¿Cómo terminó el marcador de la final Argentina vs. Francia en 2022 tras los 120 minutos (antes de los penales)?", ["2-2", "3-2", "3-3", "4-3"], 2),
    new Pregunta("historico", "final-mas-goleada", "¿Cuál es el resultado más abultado en una final de un Mundial (logrado por Brasil vs Suecia en 1958)?", ["4-1", "5-2", "3-0", "6-3"], 1),
    new Pregunta("mundial-2022", "tercer-puesto", "¿Qué selección se quedó con el tercer puesto en el Mundial de Qatar 2022?", ["Marruecos", "Francia", "Croacia", "Países Bajos"], 2),
    new Pregunta("mundial-2014", "tercer-puesto", "¿Quién obtuvo la medalla de bronce (3er puesto) en el Mundial de Brasil 2014 tras vencer al anfitrión?", ["Alemania", "Países Bajos", "Argentina", "Colombia"], 1),
    new Pregunta("reglamento", "cooling-break", "¿En qué Mundial se implementó oficialmente por primera vez el 'Cooling Break' (receso de hidratación) debido al calor?", ["Sudáfrica 2010", "Brasil 2014", "Rusia 2018", "México 1986"], 1),
    new Pregunta("reglamento", "perdida-tiempo-arquero", "Según las directrices de la FIFA para evitar la pérdida de tiempo, ¿cuántos segundos puede tener el balón un arquero antes de ser sancionado?", ["6 segundos", "8 segundos", "10 segundos", "12 segundos"], 1),
    new Pregunta("reglamento", "salida-jugador", "¿Por dónde debe salir obligatoriamente un jugador al ser sustituido para evitar demoras, según la regla actual?", ["Por la línea media únicamente", "Por donde esté el cuarto árbitro", "Por el punto más cercano de los límites del campo", "Por detrás de su propio arco"], 2),
    new Pregunta("mundial-2022", "asistidor", "¿Quién fue uno de los máximos asistidores del Mundial 2022 (empatado con otros 4 jugadores)?", ["Luka Modrić", "Antoine Griezmann", "Neymar Jr", "Ángel Di María"], 1),
    new Pregunta("mundial-2022", "jugador-joven", "¿Qué jugador recibió el premio al Mejor Jugador Joven en el Mundial de Qatar 2022?", ["Julián Álvarez", "Josko Gvardiol", "Enzo Fernández", "Jude Bellingham"], 2),
    new Pregunta("mundial-2010", "balon-de-oro", "¿Quién ganó el Balón de Oro al mejor jugador en el Mundial de Sudáfrica 2010?", ["Andrés Iniesta", "Diego Forlán", "Thomas Müller", "Wesley Sneijder"], 1)
];